# Generated by Django 3.2.11 on 2022-05-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='con_password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
